services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '${BACKEND_PORT}:3000'
    volumes:
      - ./backend:/app
    networks:
      - backend_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '${CLIENT_PORT}:3000'
    depends_on:
      - backend
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
